// Generated by gencpp from file injected_armor_msgs/ArmorDirectiveListRequest.msg
// DO NOT EDIT!


#ifndef INJECTED_ARMOR_MSGS_MESSAGE_ARMORDIRECTIVELISTREQUEST_H
#define INJECTED_ARMOR_MSGS_MESSAGE_ARMORDIRECTIVELISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <injected_armor_msgs/ArmorDirectiveReq.h>

namespace injected_armor_msgs
{
template <class ContainerAllocator>
struct ArmorDirectiveListRequest_
{
  typedef ArmorDirectiveListRequest_<ContainerAllocator> Type;

  ArmorDirectiveListRequest_()
    : armor_requests()  {
    }
  ArmorDirectiveListRequest_(const ContainerAllocator& _alloc)
    : armor_requests(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::injected_armor_msgs::ArmorDirectiveReq_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::injected_armor_msgs::ArmorDirectiveReq_<ContainerAllocator> >::other >  _armor_requests_type;
  _armor_requests_type armor_requests;





  typedef boost::shared_ptr< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmorDirectiveListRequest_

typedef ::injected_armor_msgs::ArmorDirectiveListRequest_<std::allocator<void> > ArmorDirectiveListRequest;

typedef boost::shared_ptr< ::injected_armor_msgs::ArmorDirectiveListRequest > ArmorDirectiveListRequestPtr;
typedef boost::shared_ptr< ::injected_armor_msgs::ArmorDirectiveListRequest const> ArmorDirectiveListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace injected_armor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'injected_armor_msgs': ['/home/ros/rosjava_srv_ws/src/project/injected_armor_pkgs/injected_armor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b6fe8f675c901087d462c04d41f94e1";
  }

  static const char* value(const ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b6fe8f675c90108ULL;
  static const uint64_t static_value2 = 0x7d462c04d41f94e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "injected_armor_msgs/ArmorDirectiveListRequest";
  }

  static const char* value(const ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmorDirectiveReq[] armor_requests\n\
\n\
================================================================================\n\
MSG: injected_armor_msgs/ArmorDirectiveReq\n\
string client_name\n\
string reference_name\n\
string command\n\
string primary_command_spec\n\
string secondary_command_spec\n\
string[] args\n\
";
  }

  static const char* value(const ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.armor_requests);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmorDirectiveListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::injected_armor_msgs::ArmorDirectiveListRequest_<ContainerAllocator>& v)
  {
    s << indent << "armor_requests[]" << std::endl;
    for (size_t i = 0; i < v.armor_requests.size(); ++i)
    {
      s << indent << "  armor_requests[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::injected_armor_msgs::ArmorDirectiveReq_<ContainerAllocator> >::stream(s, indent + "    ", v.armor_requests[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INJECTED_ARMOR_MSGS_MESSAGE_ARMORDIRECTIVELISTREQUEST_H
