// Generated by gencpp from file injected_armor_msgs/ArmorDirective.msg
// DO NOT EDIT!


#ifndef INJECTED_ARMOR_MSGS_MESSAGE_ARMORDIRECTIVE_H
#define INJECTED_ARMOR_MSGS_MESSAGE_ARMORDIRECTIVE_H

#include <ros/service_traits.h>


#include <injected_armor_msgs/ArmorDirectiveRequest.h>
#include <injected_armor_msgs/ArmorDirectiveResponse.h>


namespace injected_armor_msgs
{

struct ArmorDirective
{

typedef ArmorDirectiveRequest Request;
typedef ArmorDirectiveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmorDirective
} // namespace injected_armor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::injected_armor_msgs::ArmorDirective > {
  static const char* value()
  {
    return "39cbf11e18dc47e2c7b5fda84e5d8c39";
  }

  static const char* value(const ::injected_armor_msgs::ArmorDirective&) { return value(); }
};

template<>
struct DataType< ::injected_armor_msgs::ArmorDirective > {
  static const char* value()
  {
    return "injected_armor_msgs/ArmorDirective";
  }

  static const char* value(const ::injected_armor_msgs::ArmorDirective&) { return value(); }
};


// service_traits::MD5Sum< ::injected_armor_msgs::ArmorDirectiveRequest> should match 
// service_traits::MD5Sum< ::injected_armor_msgs::ArmorDirective > 
template<>
struct MD5Sum< ::injected_armor_msgs::ArmorDirectiveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::injected_armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::injected_armor_msgs::ArmorDirectiveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::injected_armor_msgs::ArmorDirectiveRequest> should match 
// service_traits::DataType< ::injected_armor_msgs::ArmorDirective > 
template<>
struct DataType< ::injected_armor_msgs::ArmorDirectiveRequest>
{
  static const char* value()
  {
    return DataType< ::injected_armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::injected_armor_msgs::ArmorDirectiveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::injected_armor_msgs::ArmorDirectiveResponse> should match 
// service_traits::MD5Sum< ::injected_armor_msgs::ArmorDirective > 
template<>
struct MD5Sum< ::injected_armor_msgs::ArmorDirectiveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::injected_armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::injected_armor_msgs::ArmorDirectiveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::injected_armor_msgs::ArmorDirectiveResponse> should match 
// service_traits::DataType< ::injected_armor_msgs::ArmorDirective > 
template<>
struct DataType< ::injected_armor_msgs::ArmorDirectiveResponse>
{
  static const char* value()
  {
    return DataType< ::injected_armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::injected_armor_msgs::ArmorDirectiveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INJECTED_ARMOR_MSGS_MESSAGE_ARMORDIRECTIVE_H
