// Generated by gencpp from file injected_armor_msgs/Words.msg
// DO NOT EDIT!


#ifndef INJECTED_ARMOR_MSGS_MESSAGE_WORDS_H
#define INJECTED_ARMOR_MSGS_MESSAGE_WORDS_H

#include <ros/service_traits.h>


#include <injected_armor_msgs/WordsRequest.h>
#include <injected_armor_msgs/WordsResponse.h>


namespace injected_armor_msgs
{

struct Words
{

typedef WordsRequest Request;
typedef WordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Words
} // namespace injected_armor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::injected_armor_msgs::Words > {
  static const char* value()
  {
    return "511abc08753d4b7c69b5d4294a4ac79d";
  }

  static const char* value(const ::injected_armor_msgs::Words&) { return value(); }
};

template<>
struct DataType< ::injected_armor_msgs::Words > {
  static const char* value()
  {
    return "injected_armor_msgs/Words";
  }

  static const char* value(const ::injected_armor_msgs::Words&) { return value(); }
};


// service_traits::MD5Sum< ::injected_armor_msgs::WordsRequest> should match 
// service_traits::MD5Sum< ::injected_armor_msgs::Words > 
template<>
struct MD5Sum< ::injected_armor_msgs::WordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::injected_armor_msgs::Words >::value();
  }
  static const char* value(const ::injected_armor_msgs::WordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::injected_armor_msgs::WordsRequest> should match 
// service_traits::DataType< ::injected_armor_msgs::Words > 
template<>
struct DataType< ::injected_armor_msgs::WordsRequest>
{
  static const char* value()
  {
    return DataType< ::injected_armor_msgs::Words >::value();
  }
  static const char* value(const ::injected_armor_msgs::WordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::injected_armor_msgs::WordsResponse> should match 
// service_traits::MD5Sum< ::injected_armor_msgs::Words > 
template<>
struct MD5Sum< ::injected_armor_msgs::WordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::injected_armor_msgs::Words >::value();
  }
  static const char* value(const ::injected_armor_msgs::WordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::injected_armor_msgs::WordsResponse> should match 
// service_traits::DataType< ::injected_armor_msgs::Words > 
template<>
struct DataType< ::injected_armor_msgs::WordsResponse>
{
  static const char* value()
  {
    return DataType< ::injected_armor_msgs::Words >::value();
  }
  static const char* value(const ::injected_armor_msgs::WordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INJECTED_ARMOR_MSGS_MESSAGE_WORDS_H
