(cl:defpackage injected_armor_msgs-srv
  (:use )
  (:export
   "ARMORDIRECTIVE"
   "<ARMORDIRECTIVE-REQUEST>"
   "ARMORDIRECTIVE-REQUEST"
   "<ARMORDIRECTIVE-RESPONSE>"
   "ARMORDIRECTIVE-RESPONSE"
   "ARMORDIRECTIVELIST"
   "<ARMORDIRECTIVELIST-REQUEST>"
   "ARMORDIRECTIVELIST-REQUEST"
   "<ARMORDIRECTIVELIST-RESPONSE>"
   "ARMORDIRECTIVELIST-RESPONSE"
   "WORDS"
   "<WORDS-REQUEST>"
   "WORDS-REQUEST"
   "<WORDS-RESPONSE>"
   "WORDS-RESPONSE"
  ))

